// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_firstHint = new UnifiedAchievement("firstHint",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "firstHint"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQAA"
#else
            "firstHint"
#endif
            );

        public static UnifiedAchievement firstHint
        {
            get { return s_firstHint; }
        }

        private static readonly UnifiedAchievement s_firstInfiniteMoves = new UnifiedAchievement("firstInfiniteMoves",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "firstInfiniteMoves"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQAQ"
#else
            "firstInfiniteMoves"
#endif
            );

        public static UnifiedAchievement firstInfiniteMoves
        {
            get { return s_firstInfiniteMoves; }
        }

        private static readonly UnifiedAchievement s_level1 = new UnifiedAchievement("level1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQAg"
#else
            "level1"
#endif
            );

        public static UnifiedAchievement level1
        {
            get { return s_level1; }
        }

        private static readonly UnifiedAchievement s_level5 = new UnifiedAchievement("level5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level5"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQAw"
#else
            "level5"
#endif
            );

        public static UnifiedAchievement level5
        {
            get { return s_level5; }
        }

        private static readonly UnifiedAchievement s_level10 = new UnifiedAchievement("level10",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level10"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQBA"
#else
            "level10"
#endif
            );

        public static UnifiedAchievement level10
        {
            get { return s_level10; }
        }

        private static readonly UnifiedAchievement s_level50 = new UnifiedAchievement("level50",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level50"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQBQ"
#else
            "level50"
#endif
            );

        public static UnifiedAchievement level50
        {
            get { return s_level50; }
        }

        private static readonly UnifiedAchievement s_level100 = new UnifiedAchievement("level100",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level100"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQBg"
#else
            "level100"
#endif
            );

        public static UnifiedAchievement level100
        {
            get { return s_level100; }
        }

        private static readonly UnifiedAchievement s_level200 = new UnifiedAchievement("level200",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level200"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQBw"
#else
            "level200"
#endif
            );

        public static UnifiedAchievement level200
        {
            get { return s_level200; }
        }

        private static readonly UnifiedAchievement s_level500 = new UnifiedAchievement("level500",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level500"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQCA"
#else
            "level500"
#endif
            );

        public static UnifiedAchievement level500
        {
            get { return s_level500; }
        }

        private static readonly UnifiedAchievement s_level1000 = new UnifiedAchievement("level1000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "level1000"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQCQ"
#else
            "level1000"
#endif
            );

        public static UnifiedAchievement level1000
        {
            get { return s_level1000; }
        }

        private static readonly UnifiedAchievement s_daily1 = new UnifiedAchievement("daily1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "daily1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQCg"
#else
            "daily1"
#endif
            );

        public static UnifiedAchievement daily1
        {
            get { return s_daily1; }
        }

        private static readonly UnifiedAchievement s_daily3 = new UnifiedAchievement("daily3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "daily3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQCw"
#else
            "daily3"
#endif
            );

        public static UnifiedAchievement daily3
        {
            get { return s_daily3; }
        }

        private static readonly UnifiedAchievement s_daily21 = new UnifiedAchievement("daily21",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "daily21"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQDA"
#else
            "daily21"
#endif
            );

        public static UnifiedAchievement daily21
        {
            get { return s_daily21; }
        }

        private static readonly UnifiedAchievement s_daily90 = new UnifiedAchievement("daily90",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "daily90"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQDQ"
#else
            "daily90"
#endif
            );

        public static UnifiedAchievement daily90
        {
            get { return s_daily90; }
        }

        private static readonly UnifiedAchievement s_play3 = new UnifiedAchievement("play3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "play3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQDg"
#else
            "play3"
#endif
            );

        public static UnifiedAchievement play3
        {
            get { return s_play3; }
        }

        private static readonly UnifiedAchievement s_play7 = new UnifiedAchievement("play7",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "play7"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQDw"
#else
            "play7"
#endif
            );

        public static UnifiedAchievement play7
        {
            get { return s_play7; }
        }

        private static readonly UnifiedAchievement s_play30 = new UnifiedAchievement("play30",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "play30"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIhYWV5awOEAIQEA"
#else
            "play30"
#endif
            );

        public static UnifiedAchievement play30
        {
            get { return s_play30; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_firstHint,
            s_firstInfiniteMoves,
            s_level1,
            s_level5,
            s_level10,
            s_level50,
            s_level100,
            s_level200,
            s_level500,
            s_level1000,
            s_daily1,
            s_daily3,
            s_daily21,
            s_daily90,
            s_play3,
            s_play7,
            s_play30,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "firstHint", s_firstHint },
            { "firstInfiniteMoves", s_firstInfiniteMoves },
            { "level1", s_level1 },
            { "level5", s_level5 },
            { "level10", s_level10 },
            { "level50", s_level50 },
            { "level100", s_level100 },
            { "level200", s_level200 },
            { "level500", s_level500 },
            { "level1000", s_level1000 },
            { "daily1", s_daily1 },
            { "daily3", s_daily3 },
            { "daily21", s_daily21 },
            { "daily90", s_daily90 },
            { "play3", s_play3 },
            { "play7", s_play7 },
            { "play30", s_play30 },
        };
    }
}
