// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string firstHint
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQAA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "firstHint";
#elif UNITY_EDITOR
                    return "firstHint";
#else
                    return string.Empty;
#endif
                }
            }

            public static string firstInfiniteMoves
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQAQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "firstInfiniteMoves";
#elif UNITY_EDITOR
                    return "firstInfiniteMoves";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level1
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQAg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level1";
#elif UNITY_EDITOR
                    return "level1";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level5
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level5";
#elif UNITY_EDITOR
                    return "level5";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level10";
#elif UNITY_EDITOR
                    return "level10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level50
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level50";
#elif UNITY_EDITOR
                    return "level50";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level100";
#elif UNITY_EDITOR
                    return "level100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level200
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level200";
#elif UNITY_EDITOR
                    return "level200";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level500
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level500";
#elif UNITY_EDITOR
                    return "level500";
#else
                    return string.Empty;
#endif
                }
            }

            public static string level1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "level1000";
#elif UNITY_EDITOR
                    return "level1000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string daily1
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "daily1";
#elif UNITY_EDITOR
                    return "daily1";
#else
                    return string.Empty;
#endif
                }
            }

            public static string daily3
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "daily3";
#elif UNITY_EDITOR
                    return "daily3";
#else
                    return string.Empty;
#endif
                }
            }

            public static string daily21
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "daily21";
#elif UNITY_EDITOR
                    return "daily21";
#else
                    return string.Empty;
#endif
                }
            }

            public static string daily90
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "daily90";
#elif UNITY_EDITOR
                    return "daily90";
#else
                    return string.Empty;
#endif
                }
            }

            public static string play3
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "play3";
#elif UNITY_EDITOR
                    return "play3";
#else
                    return string.Empty;
#endif
                }
            }

            public static string play7
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "play7";
#elif UNITY_EDITOR
                    return "play7";
#else
                    return string.Empty;
#endif
                }
            }

            public static string play30
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIhYWV5awOEAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "play30";
#elif UNITY_EDITOR
                    return "play30";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
        }
    }
}
